module.exports = [
  {
    name: "EMEIEF ANA NERY",
    classification: ["Nível I"],
    media: 474,
    category: "2",
    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EMEIEF BOA ESPERANCA",
    classification: ["Nível II"],
    media: 503,
    category: "2",
    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EEEFM EURIDICE LOPES PEDROSO",
    classification: ["Nível III"],
    media: 439,
    category: "2",
    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EMEIEF IZIDORO STEDILE",
    classification: ["Nível IV"],
    media: 460,
    category: "3",

    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EMEIEF PEDRO ALEIXO",
    classification: ["Nível V"],
    media: 488,
    category: "3",

    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EMEIEF POTY",
    classification: ["Nível V"],
    media: 590,
    category: "3",
    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EEEF TANCREDO DE ALMEIDA NEVES",
    classification: ["Nível IV"],
    media: 500,
    category: "3",
    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EMEIEF 17 DE JUNHO",
    classification: ["Nível II"],
    media: 401,
    category: "3",
    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EEEFM CORA CORALINA",
    classification: ["Nível III"],
    media: 356,
    category: "3",
    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EEEFM ANISIO TEIXEIRA",
    classification: ["Nível III"],
    media: 324,
    category: "3",
    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EMEIEF ARCO-IRIS",
    classification: ["Nível VII"],
    media: 297,
    category: "3",
    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EMEIEF JORGE TEIXEIRA",
    classification: ["Nível V"],
    media: 265,
    category: "3",
    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EMEIEF HENRIQUE DIAS",
    classification: ["Nível V"],
    media: 400,
    category: "3",
    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EMEIEF JORGE LUIZ MOULAZ",
    classification: ["Nível IV"],
    media: 509,
    category: "3",
    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EMEIEF MAFALDA RODRIGUES",
    classification: ["Nível III"],
    media: 354,
    category: "3",
    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EEEFM MIGRANTES",
    classification: ["Nível II"],
    media: 456,
    category: "3",
    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EEEMTI HEITOR VILLA LOBOS",
    classification: ["Nível V"],
    media: 314,
    category: "3",

    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EMEIEF CECILIA MEIRELES",
    classification: ["Nível V"],
    media: 356,
    category: "3",

    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EEEFM PLANALTO",
    classification: ["Nível III"],
    media: 476,
    category: "2",

    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EEEFM PLANALTO AYRTON",
    classification: ["Nível III"],
    media: 280,
    category: "2",

    uf: "CE",
    municipio: "Fortaleza",
    quantidadeAlunos: 23,
  },
  {
    name: "EEEFM JOSE ANCHIETA",
    classification: ["Nível V"],
    media: 267,
    category: "2",
    uf: "RO",
    municipio: "Rondônia",
    quantidadeAlunos: 2,
  },
  {
    name: "EEEFM PAULO FREIRE",
    classification: ["Nível IV"],
    media: 372,
    category: "1",
    uf: "RO",
    municipio: "Rondônia",
    quantidadeAlunos: 2,
  },
  {
    name: "EEEFM JOSE MAURO",
    classification: ["Nível III"],
    media: 569,
    category: "1",
    uf: "RO",
    municipio: "Rondônia",
    quantidadeAlunos: 2,
  },
  {
    name: "EEEFM MONTEIRO LOBATO",
    classification: ["Nível IV"],
    media: 382,
    category: "1",
    uf: "RO",
    municipio: "Rondônia",
    quantidadeAlunos: 2,
  },
  {
    name: "EEEFM PLANALTO BERNARDO",
    classification: ["Nível IV"],
    media: 409,
    category: "1",
    uf: "RO",
    municipio: "Rondônia",
    quantidadeAlunos: 2,
  },
  {
    name: "EEEFM CLODOALDO NUNES",
    classification: ["Nível III"],
    media: 370,
    category: "1",
    uf: "RO",
    municipio: "Rondônia",
    quantidadeAlunos: 2,
  },
  {
    name: "EEEFM JOSE DE ALMEIDA",
    classification: ["Nível V"],
    media: 460,
    category: "1",
    uf: "RO",
    municipio: "Rondônia",
    quantidadeAlunos: 19,
  },
  {
    name: "EEEFM PLANALTO CASTRO ALVES",
    classification: ["Nível VI"],
    media: 570,
    category: "1",
    uf: "RO",
    municipio: "Rondônia",
    quantidadeAlunos: 21,
  },
  {
    name: "EEEFM DOM JOÃO VI",
    classification: ["Nível V"],
    media: 394,
    category: "1",
    uf: "RO",
    municipio: "Rondônia",
    quantidadeAlunos: 2,
  },
];
